from __future__ import annotations
from pathlib import Path
import re
import warnings
import pandas as pd

EXCEL_EXTS = {'.xlsx', '.xlsm', '.xls'}
TABLE_EXTS = EXCEL_EXTS | {'.csv', '.txt'}
EMPTY_VALUES = {'', 'nan', 'none', 'null', 'notdefined', 'not defined', '-', '--', '—', 'n/a', 'na', '<na>'}

CANONICAL_HEADER_HINTS = [
    'rbr-object_id','object_id','object id','objectid','rbr-object_idparent','parent',
    'rbr-discipline_code','discipline','rbr-occ','occ','rbr-type_number','type_number','type number','typenumber',
    'rbr-pr_code','pr_code','pr-code','product code','product_code','uniclass','classification',
    'rbr-quantity','quantity','qty','amount','total','rbr-units','rbr-unit','unit','units','measurement unit',
    'name','element','description','material','route','phase','volume','area','length'
]


def as_text(v) -> str:
    if v is None:
        return ''
    try:
        if pd.isna(v):
            return ''
    except Exception:
        pass
    return str(v).replace('\ufeff','').strip()


def is_empty(v) -> bool:
    return as_text(v).strip().lower() in EMPTY_VALUES


def norm_col(c: str) -> str:
    return re.sub(r'[^a-z0-9]', '', as_text(c).lower())


def _row_values(row) -> list[str]:
    return [as_text(v) for v in list(row)]


def _header_score(vals: list[str], data_after: pd.DataFrame | None = None) -> float:
    vals_clean = [v for v in vals if v and v.lower() not in EMPTY_VALUES]
    if not vals_clean:
        return -100.0
    joined = ' | '.join(v.lower() for v in vals_clean)
    score = 0.0
    # exact/semantic header tokens
    for hint in CANONICAL_HEADER_HINTS:
        if hint in joined:
            score += 10
    # reward multiple non-empty candidate headers, penalise title rows
    score += min(len(vals_clean), 40) * 0.7
    if any(t in joined for t in ['rail baltica - qex report','rail baltica - qto report','report template']):
        score -= 35
    if len(vals_clean) <= 2 and len(joined) > 20:
        score -= 15
    # reward header-like short text, penalize long descriptive cells
    score += sum(1 for v in vals_clean if len(v) <= 35) * 0.25
    score -= sum(1 for v in vals_clean if len(v) > 80) * 0.5
    # reward evidence of BIM rows after the header
    if data_after is not None and not data_after.empty:
        sample = ' '.join(as_text(x) for x in data_after.iloc[:20, :min(30, data_after.shape[1])].values.ravel())
        if re.search(r'\b(?:STR|DR|RO|BR|GE|EL|TP|AR|UD)-[A-Z0-9]{2,5}-[A-Z0-9]{2,5}-\d{4}\b', sample, re.I):
            score += 15
        if re.search(r'\b(?:Pr|Ss|En|EF|SL|TE|PM|Zz)_\d{2}_\d{2}_\d{2}', sample):
            score += 10
        if re.search(r'\b(?:m2|m3|m²|m³|pcs|pc|m|kg|t)\b', sample, re.I):
            score += 3
    return float(score)


def clean_df(df: pd.DataFrame) -> pd.DataFrame:
    if df is None:
        return pd.DataFrame()
    df = df.copy()
    df = df.dropna(how='all')
    if df.empty:
        return pd.DataFrame()
    cols = []
    seen = {}
    for i, c in enumerate(df.columns):
        name = as_text(c)
        if not name or name.lower().startswith('unnamed'):
            name = f'Column_{i+1}'
        base = name
        if base in seen:
            seen[base] += 1
            name = f'{base}_{seen[base]}'
        else:
            seen[base] = 0
        cols.append(name)
    df.columns = cols
    # remove empty unnamed columns, but keep columns with content even if autogenerated
    keep = []
    for c in df.columns:
        if c.startswith('Column_') and df[c].apply(is_empty).all():
            continue
        keep.append(c)
    return df[keep].reset_index(drop=True)


def _make_df_from_raw(raw: pd.DataFrame, header_row: int, nrows: int | None = None) -> pd.DataFrame:
    vals = _row_values(raw.iloc[header_row].tolist())
    data = raw.iloc[header_row + 1:].copy()
    if nrows is not None:
        data = data.iloc[:nrows]
    # ensure header width matches data width
    if len(vals) < data.shape[1]:
        vals += [f'Column_{i+1}' for i in range(len(vals), data.shape[1])]
    vals = vals[:data.shape[1]]
    data.columns = vals
    return clean_df(data)


def infer_table_from_raw(raw: pd.DataFrame, nrows: int | None = None, max_scan_rows: int = 120) -> tuple[pd.DataFrame, dict]:
    if raw is None or raw.empty:
        return pd.DataFrame(), {'header_row': None, 'score': -100, 'reason': 'empty raw sheet'}
    raw = raw.dropna(how='all')
    if raw.empty:
        return pd.DataFrame(), {'header_row': None, 'score': -100, 'reason': 'empty raw sheet'}
    best = (pd.DataFrame(), {'header_row': None, 'score': -100.0, 'reason': 'no header found'})
    rows_to_scan = min(max_scan_rows, len(raw))
    for i in range(rows_to_scan):
        vals = _row_values(raw.iloc[i].tolist())
        sc = _header_score(vals, raw.iloc[i+1:])
        if sc > best[1]['score']:
            df = _make_df_from_raw(raw, i, nrows=nrows)
            if not df.empty and len(df.columns) > 1:
                best = (df, {'header_row': i + 1, 'score': sc, 'reason': 'inferred header row'})
    return best


def _read_excel_best(path: Path, nrows: int | None = None) -> tuple[pd.DataFrame, dict]:
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        try:
            xls = pd.ExcelFile(path)
        except Exception as e:
            return pd.DataFrame(), {'error': f'Excel unreadable: {e}', 'sheet': None, 'header_row': None, 'score': -100}
        best_df = pd.DataFrame()
        best_meta = {'sheet': None, 'header_row': None, 'score': -100.0, 'reason': 'no readable table'}
        for sheet in xls.sheet_names[:40]:
            try:
                raw = pd.read_excel(path, sheet_name=sheet, dtype=str, header=None)
            except Exception:
                continue
            raw = raw.iloc[:, :120]
            df, meta = infer_table_from_raw(raw, nrows=nrows, max_scan_rows=140)
            meta['sheet'] = sheet
            if meta.get('score', -100) > best_meta.get('score', -100) and not df.empty:
                best_df, best_meta = df, meta
        return best_df, best_meta


def _read_csv_best(path: Path, nrows: int | None = None) -> tuple[pd.DataFrame, dict]:
    best_df = pd.DataFrame(); best_meta = {'score': -100, 'delimiter': None, 'encoding': None, 'header_row': None}
    for enc in ['utf-8-sig', 'utf-8', 'latin1', 'cp1252']:
        for sep in [None, ';', ',', '\t', '|']:
            try:
                raw = pd.read_csv(path, dtype=str, encoding=enc, sep=sep, engine='python', header=None)
            except Exception:
                continue
            df, meta = infer_table_from_raw(raw, nrows=nrows, max_scan_rows=80)
            if not df.empty and meta.get('score', -100) > best_meta.get('score', -100):
                best_df, best_meta = df, {**meta, 'delimiter': sep or 'auto', 'encoding': enc}
    return best_df, best_meta


def read_table_with_meta(path: str | Path, nrows: int | None = None) -> tuple[pd.DataFrame, dict]:
    path = Path(path)
    if not path.exists() or path.name.startswith('~$'):
        return pd.DataFrame(), {'error': 'missing or temporary file', 'path': str(path)}
    suffix = path.suffix.lower()
    if suffix in EXCEL_EXTS:
        df, meta = _read_excel_best(path, nrows=nrows)
    elif suffix in {'.csv', '.txt'}:
        df, meta = _read_csv_best(path, nrows=nrows)
    else:
        return pd.DataFrame(), {'error': 'unsupported extension', 'path': str(path)}
    meta['path'] = str(path)
    meta['file'] = path.name
    meta['rows'] = len(df)
    meta['columns'] = list(df.columns)[:80]
    return df, meta


def read_table(path: str | Path, nrows: int | None = None) -> pd.DataFrame:
    return read_table_with_meta(path, nrows=nrows)[0]


def find_col(df: pd.DataFrame, candidates: list[str]) -> str | None:
    if df is None or df.empty:
        return None
    norm_map = {norm_col(c): c for c in df.columns}
    cand_norm = [norm_col(c) for c in candidates]
    # exact normalized
    for cn in cand_norm:
        if cn in norm_map:
            return norm_map[cn]
    # candidate within column and vice versa
    for cn in cand_norm:
        for k, orig in norm_map.items():
            if cn and (cn in k or k in cn):
                return orig
    # looser synonym matching for very messy headers
    synonyms = {
        'objectid': ['elementid', 'assetid', 'idobject'],
        'typenumber': ['typenr', 'typeno', 'typenumber'],
        'prcode': ['productcode', 'payitem', 'itemcode', 'uniclasscode'],
        'quantity': ['qty', 'amount', 'totalquantity'],
        'unit': ['units', 'measurementunit', 'uom'],
    }
    for cn in cand_norm:
        for syn in synonyms.get(cn, []):
            if syn in norm_map:
                return norm_map[syn]
            for k, orig in norm_map.items():
                if syn in k or k in syn:
                    return orig
    return None


def to_num(s):
    ser = pd.Series(s).astype(str).str.strip()
    ser = ser.str.replace('\u00a0','', regex=False).str.replace(' ', '', regex=False)
    # preserve decimal comma if no decimal point exists
    ser = ser.str.replace(',', '.', regex=False)
    return pd.to_numeric(ser, errors='coerce')
